language: rust

sudo: required
services:
  - docker

git:
  depth: 1

os:
  - linux
  - osx
  - windows

rust:
  - stable
  - nightly

matrix:
  fast_finish: true
  include:
    - if: tag IS present
      os: linux
      rust: stable
      env: ARCH=i386
  allow_failures:
    - rust: nightly
    - os: windows

install: ci/install.sh
script: ci/script.sh
before_deploy: ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: "xB+6PK3qXDNCrdRGhmt8YDtOJaNlewnWxXwK9Kq8aWNuiZ7bbYH1cobo4fuTuOVQ2vfdEhAagZjV6OyFRxTZaqIEBDyQaSc9AYUBw9NGbqItqQ0hsKaVwNjL7qNCmEXepzzEtGvScnl5v7SYPUKTjxhPOghmLfHB9ZaGvmKgO3DJ9177degcc9uJLNrBi2T0vOccR+e9W+vWT7RCCEAgP37RnYSIsLYR22gQLZ/maR+Z5ltUPAdZhJSZ/9cq8afDl0m01wBcOWtOdhzU0GhAUEw5AdsvttIZPeSsfy2HmxoumeVDmg1WUk8xIT0A62Ako24WFb+dYAPJfq4MIsh7mMBLnM8JqQ+aGyBPyvKJYtdWXaeFIJOSPeR5sCPZbBL/MBF9av7nk4UDnzcPlj2NDGMRKMih9tRG9W965LbBfltWMcaxPWGbWBNg7lUqxDd9+eZquFon2RoHdKjtAWetXAuLQ85IVYoD2uv3MZUTyruolR+eOV1IBflcIRkX4w/kFAFaceN7GMhXRxb2gAOOBIZy8m3vN/aQXYVEFJazIK/MruRnn8J1MECvtWFQeuprgS35OJVYH4n5Mq647oIumYWh9rPBYmkCyeUTTm0fJOcKinm0E7kFT/MvbSqhr51IbAQ/kRtJD8xcK+sohMg2mFK4Bpy/fqtq8a1zEsSEZ1M="
  skip_cleanup: true
  file_glob: true
  file: "./target/deploy/*"
  on:
    tags: true
    rust: stable
    repo: zacps/alacritty
    branch: windows-zip-test
